package com.example.pyneebackend.entities;

import jakarta.persistence.*;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "feedback")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Feedback {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "feedback_id")
    private Long feedbackId;

//    @ManyToOne
//    @JoinColumn(name = "customer_id")
//    private Customer customer;

    @ManyToOne
    @JoinColumn(name = "tour_for_sale_id")
    private TourForSale tourForSale;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "creation_date")
    private Date creationDate;

    private String description;

    // Getters and setters are still generated by @Data
}
